// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBomHdW-tAz5iELdVChGr6rE-CGuPRzCT8',
    appId: '1:443697553984:web:a4ceaacdbd5e476a7a75a5',
    messagingSenderId: '443697553984',
    projectId: 'mealcrunchy-20260604',
    authDomain: 'mealcrunchy-20260604.firebaseapp.com',
    storageBucket: 'mealcrunchy-20260604.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWMc2uvf_t-_QW2JbUL_Jtxc8zN1eg99M',
    appId: '1:443697553984:android:25fa8ed92935eec47a75a5',
    messagingSenderId: '443697553984',
    projectId: 'mealcrunchy-20260604',
    storageBucket: 'mealcrunchy-20260604.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvwrTcD7WdilIGJ2GVE82WpVTIbBcnUks',
    appId: '1:443697553984:ios:5f7fccb3339f32b57a75a5',
    messagingSenderId: '443697553984',
    projectId: 'mealcrunchy-20260604',
    storageBucket: 'mealcrunchy-20260604.firebasestorage.app',
    iosBundleId: 'com.cyrilbelin.mealcrunchy',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvwrTcD7WdilIGJ2GVE82WpVTIbBcnUks',
    appId: '1:443697553984:ios:5f7fccb3339f32b57a75a5',
    messagingSenderId: '443697553984',
    projectId: 'mealcrunchy-20260604',
    storageBucket: 'mealcrunchy-20260604.firebasestorage.app',
    iosBundleId: 'com.cyrilbelin.mealcrunchy',
  );
}
